# Generated by Django 3.1.7 on 2021-03-04 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('cataract', 'Cataract'), ('vitreo', 'Vitreoretinal'), ('optometry', 'Optometry'), ('multi', 'Multidisciplinary'), ('plastic', 'Plastic and Reconstructive surgery'), ('onco', 'Ocular oncology'), ('glaucoma', 'Glaucoma'), ('pediatrics', 'Pediatrics')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='Mr', max_length=5)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('description', models.TextField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=100)),
                ('event_format', models.CharField(choices=[('live', 'Live'), ('online', 'Online')], default='online', max_length=50)),
                ('main_language', models.CharField(choices=[('EN', 'English'), ('IT', 'Italian'), ('FR', 'French'), ('DE', 'German'), ('RU', 'Russian')], default='EN', max_length=50)),
                ('event_url', models.URLField(blank=True)),
                ('event_date_start', models.DateField(db_index=True, verbose_name='Start date')),
                ('event_time_start', models.TimeField(default='09:00')),
                ('event_date_finish', models.DateField(auto_now=True, verbose_name='End date')),
                ('event_time_finish', models.TimeField(default='18:00')),
                ('is_cme', models.BooleanField(db_index=True, default=False, verbose_name='CME credits')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.entity')),
                ('speakers', models.ManyToManyField(blank=True, to='events.Faculty', verbose_name='presenter')),
                ('tags', models.ManyToManyField(blank=True, to='events.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=250, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.faculty')),
            ],
        ),
    ]
