# Generated by Django 3.1.7 on 2021-03-05 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name_plural': 'Agenda'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_finish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='events.Faculty'),
        ),
    ]
