# Generated by Django 3.1.7 on 2021-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210305_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='event',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
