# Generated by Django 3.1.7 on 2021-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
