# Generated by Django 3.1.7 on 2021-03-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210305_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='draft',
            new_name='global_visibility',
        ),
    ]
